export declare const APP_NAME = "agent-study";
export * from "./enums";
export * from "./common";
export * from "./system";
export * from "./department";
export * from "./user";
export * from "./role";
export * from "./menu";
export * from "./auth";
export * from "./requirement";
