import { z } from 'zod';
import type { CommonStatus, MenuType } from './enums';
export type MenuNode = {
    id: string;
    parentId: string | null;
    type: MenuType;
    name: string;
    path?: string | null;
    component?: string | null;
    icon?: string | null;
    permissionCode?: string | null;
    visible: boolean;
    status: CommonStatus;
    sort: number;
    children?: MenuNode[];
};
export declare const menuNodeSchema: z.ZodType<MenuNode>;
export declare const menuDetailSchema: z.ZodObject<{
    id: z.ZodString;
    systemId: z.ZodString;
    parentId: z.ZodNullable<z.ZodString>;
    type: z.ZodEnum<["DIR", "MENU", "BUTTON"]>;
    name: z.ZodString;
    path: z.ZodNullable<z.ZodString>;
    component: z.ZodNullable<z.ZodString>;
    icon: z.ZodNullable<z.ZodString>;
    permissionCode: z.ZodNullable<z.ZodString>;
    visible: z.ZodBoolean;
    status: z.ZodEnum<["ENABLED", "DISABLED"]>;
    sort: z.ZodNumber;
    createdAt: z.ZodString;
    updatedAt: z.ZodString;
}, "strip", z.ZodTypeAny, {
    sort: number;
    id: string;
    name: string;
    type: "DIR" | "MENU" | "BUTTON";
    path: string | null;
    status: "DISABLED" | "ENABLED";
    createdAt: string;
    updatedAt: string;
    parentId: string | null;
    systemId: string;
    component: string | null;
    icon: string | null;
    permissionCode: string | null;
    visible: boolean;
}, {
    sort: number;
    id: string;
    name: string;
    type: "DIR" | "MENU" | "BUTTON";
    path: string | null;
    status: "DISABLED" | "ENABLED";
    createdAt: string;
    updatedAt: string;
    parentId: string | null;
    systemId: string;
    component: string | null;
    icon: string | null;
    permissionCode: string | null;
    visible: boolean;
}>;
export type MenuDetail = z.infer<typeof menuDetailSchema>;
export declare const createMenuSchema: z.ZodEffects<z.ZodEffects<z.ZodObject<{
    systemId: z.ZodString;
    parentId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    type: z.ZodEnum<["DIR", "MENU", "BUTTON"]>;
    name: z.ZodString;
    path: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    component: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    icon: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    permissionCode: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    visible: z.ZodDefault<z.ZodBoolean>;
    sort: z.ZodDefault<z.ZodNumber>;
    status: z.ZodDefault<z.ZodEnum<["ENABLED", "DISABLED"]>>;
}, "strip", z.ZodTypeAny, {
    sort: number;
    name: string;
    type: "DIR" | "MENU" | "BUTTON";
    status: "DISABLED" | "ENABLED";
    systemId: string;
    visible: boolean;
    path?: string | null | undefined;
    parentId?: string | null | undefined;
    component?: string | null | undefined;
    icon?: string | null | undefined;
    permissionCode?: string | null | undefined;
}, {
    name: string;
    type: "DIR" | "MENU" | "BUTTON";
    systemId: string;
    sort?: number | undefined;
    path?: string | null | undefined;
    status?: "DISABLED" | "ENABLED" | undefined;
    parentId?: string | null | undefined;
    component?: string | null | undefined;
    icon?: string | null | undefined;
    permissionCode?: string | null | undefined;
    visible?: boolean | undefined;
}>, {
    sort: number;
    name: string;
    type: "DIR" | "MENU" | "BUTTON";
    status: "DISABLED" | "ENABLED";
    systemId: string;
    visible: boolean;
    path?: string | null | undefined;
    parentId?: string | null | undefined;
    component?: string | null | undefined;
    icon?: string | null | undefined;
    permissionCode?: string | null | undefined;
}, {
    name: string;
    type: "DIR" | "MENU" | "BUTTON";
    systemId: string;
    sort?: number | undefined;
    path?: string | null | undefined;
    status?: "DISABLED" | "ENABLED" | undefined;
    parentId?: string | null | undefined;
    component?: string | null | undefined;
    icon?: string | null | undefined;
    permissionCode?: string | null | undefined;
    visible?: boolean | undefined;
}>, {
    sort: number;
    name: string;
    type: "DIR" | "MENU" | "BUTTON";
    status: "DISABLED" | "ENABLED";
    systemId: string;
    visible: boolean;
    path?: string | null | undefined;
    parentId?: string | null | undefined;
    component?: string | null | undefined;
    icon?: string | null | undefined;
    permissionCode?: string | null | undefined;
}, {
    name: string;
    type: "DIR" | "MENU" | "BUTTON";
    systemId: string;
    sort?: number | undefined;
    path?: string | null | undefined;
    status?: "DISABLED" | "ENABLED" | undefined;
    parentId?: string | null | undefined;
    component?: string | null | undefined;
    icon?: string | null | undefined;
    permissionCode?: string | null | undefined;
    visible?: boolean | undefined;
}>;
export type CreateMenuInput = z.infer<typeof createMenuSchema>;
export declare const updateMenuSchema: z.ZodObject<{
    parentId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    type: z.ZodOptional<z.ZodEnum<["DIR", "MENU", "BUTTON"]>>;
    name: z.ZodOptional<z.ZodString>;
    path: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    component: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    icon: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    permissionCode: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    visible: z.ZodOptional<z.ZodBoolean>;
    sort: z.ZodOptional<z.ZodNumber>;
    status: z.ZodOptional<z.ZodEnum<["ENABLED", "DISABLED"]>>;
}, "strip", z.ZodTypeAny, {
    sort?: number | undefined;
    name?: string | undefined;
    type?: "DIR" | "MENU" | "BUTTON" | undefined;
    path?: string | null | undefined;
    status?: "DISABLED" | "ENABLED" | undefined;
    parentId?: string | null | undefined;
    component?: string | null | undefined;
    icon?: string | null | undefined;
    permissionCode?: string | null | undefined;
    visible?: boolean | undefined;
}, {
    sort?: number | undefined;
    name?: string | undefined;
    type?: "DIR" | "MENU" | "BUTTON" | undefined;
    path?: string | null | undefined;
    status?: "DISABLED" | "ENABLED" | undefined;
    parentId?: string | null | undefined;
    component?: string | null | undefined;
    icon?: string | null | undefined;
    permissionCode?: string | null | undefined;
    visible?: boolean | undefined;
}>;
export type UpdateMenuInput = z.infer<typeof updateMenuSchema>;
export declare const menuTreeQuerySchema: z.ZodObject<{
    systemId: z.ZodString;
}, "strip", z.ZodTypeAny, {
    systemId: string;
}, {
    systemId: string;
}>;
export type MenuTreeQuery = z.infer<typeof menuTreeQuerySchema>;
